      SUBROUTINE CMOD3                                                          
C                                                                               
C  get derived vars that are implied by all present sampled vars                
C                                                                               
      INCLUDE "gppdata.h"                                                       
      CALL VERIF('QCWC  ','QCW   ')                                             
      CALL VERIF('QCGC  ','QCG   ')                                             
      CALL VERIF('QCBC  ','QCB   ')                                             
      CALL VERIF('QCFC  ','QCF   ')                                             
      CALL VERIF('CSUBP ','DPSF  ')                                             
      CALL VERIF('DPTC  ','DPT   ')                                             
      CALL VERIF('DPBC  ','DPB   ')                                             
      CALL VERIF('PSFC  ','PSF   ')                                             
      CALL VERIF('PSBC  ','PSB   ')                                             
      CALL VERIF('PSWC  ','PSW   ')                                             
      CALL VERIF('PSFDC ','PSFD  ')                                             
      CALL VERIF('ATW   ','TTW   ')                                             
      CALL VERIF('ATWH  ','TTWH  ')                                             
      CALL VERIF('ATF   ','TTF   ')                                             
      CALL VERIF('ATFH  ','TTFH  ')                                             
      CALL VERIF('ATB   ','TTB   ')                                             
      CALL VERIF('ATBH  ','TTBH  ')                                             
      CALL VERIF('ATRF  ','TTRF  ')                                             
      CALL VERIF('ATKP  ','TTKP  ')                                             
      CALL VERIF('LWCC  ','LWC   ')                                             
      CALL VERIF('PLWCC ','PLWC  ')                                             
      CALL VERIF('IRTC  ','IRT   ')                                             
      CALL VERIF('IRBC  ','IRB   ')                                             
      CALL VERIF('AKFXR ','AFIXR ')                                             
      CALL VERIF('GUSTO ','AFIXR ')                                             
      CALL VERIF('AKFXL ','AFIXL ')                                             
      CALL VERIF('SSFXB ','BFIXB ')                                             
      CALL VERIF('SSFXT ','BFIXT ')                                             
      CALL VERIF('ATAKP ','ADIF  ')                                             
      CALL VERIF('GUSTO ','ADIF  ')                                             
      CALL VERIF('SSLPP ','BDIF  ')                                             
      CALL VERIF('DMECH ','DME1  ')                                             
      CALL VERIF('DMEDI ','DME1  ')                                             
      CALL VERIF('DMEFLG','DME1  ')                                             
      CALL VERIF('QCRC  ','ADIFR ')                                             
      CALL VERIF('AKRD  ','ADIFR ')                                             
      CALL VERIF('SSRD  ','BDIFR ')                                             
      CALL VERIF('TASR  ','ADIFR ')                                             
      CALL VERIF('GUSTR ','ADIFR ')                                             
      CALL VERIF('DRICE ','RICE  ')                                             
      CALL VERIF('RHOLAR','VLA   ')                                             
      CALL VERIF('RHOLAF','VLA   ')                                             
      CALL VERIF('DFDLA ','VLA   ')                                             
      CALL VERIF('DPLAC ','VLA   ')                                             
      CALL VERIF('DVALUR','HGME  ')                                             
      CALL VERIF('DVALU ','HGME  ')                                             
      RETURN                                                                    
      END                                                                       
